---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-server
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
    app.kubernetes.io/name: zabbix-server
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
spec:
  type: {{ .Values.zabbixserver.service.type }}
  {{- if .Values.zabbixserver.service.clusterIP }}
  clusterIP: {{ .Values.zabbixserver.service.clusterIP }}
  {{- end }}
  {{- if .Values.zabbixserver.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.zabbixserver.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixserver.service.port }}
      targetPort: 10051
      name: zabbix-server
      protocol: TCP
    - port: 10052
      targetPort: 10052
      protocol: TCP
      name: zabbix-jmx
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
---
  {{- if .Values.zabbixagent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-agent
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-agent
    app.kubernetes.io/name: zabbix-agent
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-agent
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-agent
spec:
  type: {{ .Values.zabbixagent.service.type }}
  {{- if .Values.zabbixagent.service.clusterIP }}
  clusterIP: {{ .Values.zabbixagent.service.clusterIP }}
  {{- end }}
  {{- if .Values.zabbixserver.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.zabbixserver.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixagent.service.port }}
      targetPort: 10050
      protocol: TCP
      name: zabbix-agent
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
    {{- end }}
---
  {{- if .Values.zabbixweb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-web
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-web
    app.kubernetes.io/name: zabbix-web
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-web
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-web
spec:
  type: {{ .Values.zabbixweb.service.type }}
  {{- if .Values.zabbixweb.service.clusterIP }}
  clusterIP: {{ .Values.zabbixweb.service.clusterIP }}
  {{- end }}
  {{- if .Values.zabbixserver.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.zabbixserver.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixweb.service.port }}
      targetPort: 8080
      protocol: TCP
      name: zabbix-web
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-web
  {{- end }}
---
  {{- if .Values.zabbixproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-proxy
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-proxy
    app.kubernetes.io/name: zabbix-proxy
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-proxy
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-proxy
spec:
  type: {{ .Values.zabbixproxy.service.type }}
  {{- if .Values.zabbixproxy.service.clusterIP }}
  clusterIP: {{ .Values.zabbixproxy.service.clusterIP }}
  {{- end }}
  {{- if .Values.zabbixserver.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.zabbixserver.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixproxy.service.port }}
      targetPort: 10051
      protocol: TCP
      name: zabbix-proxy
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-proxy
    {{- end }}